version: '3.8'

services:

  server:
    container_name: server
    build: ./
    command: bash -c "alembic upgrade head && pytest && python run.py"
    ports:
      - "3002:3002"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    container_name: worker
    build: ./
    command: bash -c "sleep 10 && python run.py worker"
    networks:
      - network
    depends_on:
      server:
        condition: service_started

  postgres:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  network:
