version: '3.8'

services:

  server:
    container_name: server
    build: ./
    command: bash -c "alembic upgrade head && alembic revision --autogenerate -m "Added all" && alembic upgrade head && python run.py"
    ports:
      - 3002:3002
    networks:
      - network
    depends_on:
      server_test:
        condition: service_completed_successfully

  worker:
    container_name: worker
    build: ./
    command: bash -c "python run.py worker"
    networks:
      - network
    depends_on:
      server_test:
        condition: service_completed_successfully

  server_test:
    container_name: server_test
    build: ./
    command: bash -c "pytest"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  network:
